Version 1.1
agriculture-vlab/avl-dataset-convention pull request #2
Opened 2021-10-01 14:28 UTC by forman

I added

* convention section about consolidation of metadata;
* convention section about Zip archives.

2021-10-01 14:50 UTC, lnicola commented on src/main.py
> +    dataset.to_zarr(file_path, consolidated=True)
FWIW, the default is to write consolidated metadata, so this makes things more clear but is optional.

2021-10-01 14:50 UTC, lnicola approved these changes

2021-10-01 14:59 UTC, lnicola commented on src/main.py
> +    dataset.to_zarr(file_path, consolidated=True)
Also, `to_zarr` can write a ZIP file directly, although I couldn't get it to work right.

2021-10-08 13:03 UTC, pont-us requested changes
Just some minor wording changes requested.

2021-10-08 13:03 UTC, pont-us commented on CONVENTION.md
> +The consolidated format of the consolidated metadata must be JSON. It is a
```suggestion
The format of the consolidated metadata must be JSON. It is a 
```

2021-10-08 13:03 UTC, pont-us commented on CONVENTION.md
> +With other words, the keys of the entries in such an archive should not
```suggestion
In other words, the keys of the entries in such an archive should not 
```

2021-10-08 13:03 UTC, pont-us commented on src/main.py
> +    dataset.to_zarr(file_path, consolidated=True)
I approve of the explicit consolidation parameter: as Laurențiu says, it makes things clearer, but it also broadens compatibility (since xarray only consolidates by default since v0.19.0).

2021-10-08 13:03 UTC, pont-us commented on CONVENTION.md
> +have a common prefix as it is often the case when directories are zipped
```suggestion
have a common prefix as is often the case when directories are zipped 
```

2021-10-27 16:42 UTC, forman commented on src/main.py
> +    dataset.to_zarr(file_path, consolidated=True)
I'll do.

2021-10-27 16:42 UTC, merged